### ISSUE TITLE
Can’t get past login screen on Google Hub

### ISSUE THREAD

**Issue by sylvainvrolijk** [AlexxIT/DashCast#14]
I have a script which casts the dashboard. I have the following in configuration.yaml:

```
homeassistant:
  auth_providers:
      - type: homeassistant
      - type: trusted_networks
        trusted_networks:
          - Xxx.xxx.x.xxx  # my Google Nest Hub IP
        trusted_users:
          Xxx.xxx.x.xxx: 'User id between brackets' 
        allow_bypass_login: true
```

However I cannot get past the login screen. I do not see a ‘hidden button’ to continue. What am I missing?

**Comment by AlexxIT** [comment]
I don't know. If your want to cast lovelace - it's better to use Hass built-in feature

**Comment by kevarch** [comment]
I had this issue.  All you need to do is flip the order of the auth_providers. I am not sure what is happening on the back side, but it seems home assistant will try each login method in order before proceeding to the next. 

Example:

```
homeassistant:
  auth_providers:
      - type: trusted_networks
        trusted_networks:
          - Xxx.xxx.x.xxx  # my Google Nest Hub IP
        trusted_users:
          Xxx.xxx.x.xxx: 'User id between brackets' 
        allow_bypass_login: true
      - type: homeassistant
```

**Comment by 0000Max0000** [comment]
Why is this not working ?
```
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.52
      trusted_users:
        192.168.0.52: "5984663020614e85afa4ccf81ec39dba"
    - type: homeassistant
`````
I see the select button for half a second and than the login en password screen apears.

**Comment by kevarch** [comment]
Couple of possibilities:

1. You're missing the "allow_bypass_login: true" line.
2. The IP addresses under trusted_networks are expected to be in CIDR range format.  Use #.#.#.#/32 if you only want a single IP. See [https://www.home-assistant.io/docs/authentication/providers/](https://www.home-assistant.io/docs/authentication/providers/)

**Comment by adr1200c** [comment]
Check the ha logs on invalid logins.
You might see a different ip address for your google nest hub.

On the WiFi network mine had an ip but the nest comes in with some other ip.
When login appears on hub just press enter and in the ha logs file you see diff ip address.
Then add that ip to trusted network 
Happened to me

**Comment by onund** [comment]
Not sure if this is still an issue.  I ran into this after updating to 2026.5.  I had two mistakes and one surprise that prevented my Google Hub from connecting.  AI was not at all helpful on this one.  The HA [Authentication provides documentation](http://home-assistant.io/docs/authentication/providers/) was very helpful, however.  All the info to fix it was there, but maybe not obviously laid out for everyone to understand.  Here is my breakdown for those trying to together old posts, AI recommendations, and the very nice HA documentation

**Problem 1: auth_providers in the wrong order**

My setup was something like this:
```
homeassistant:
  auth_providers:
      - type: homeassistant
      - type: trusted_networks
        trusted_networks:
          - 192.168.0.0/24  # My main network
        trusted_users:
          192.168.0.10: HUB_USER_ID # Google Hub IP
          192.168.0.11: PHONE_USER_ID # Someones phone
          192.168.0.12: HUB_USER_ID # Another tablet for dashboard displays
        allow_bypass_login: true
```

The problem is HA servers up the authentication providers in sequential order.  When my Google Hub turns on, HA finds Google Hub can log in using the default “type: homeassistant” then stops looking.
Fix is as others said, move “-type: homeassistant” to the bottom, after “-type: trusted_network”
_This is what the documentation says, but it seems to still work after fix 2?_

**Problem 2: You cannot trust something in trusted_proxies**

I use Caddy for reverse proxy.  I was debugging something so my trusted proxy looked like this:

```
http:
  use_x_forwarded_for: true
    trusted_proxies:
      - xxx.xxx.xxx.xxx #stuff not relevant to the discussion
      - 192.168.0.0/24  # Caddy reverse proxy IPv4 address
```
Everything on my main network was added to the trusted_proxies list and failed authentication (the docs warned against this, AI didn't pick it up).  
Fix: Change the Caddy masked address to the specific Caddy server address – 192.168.0.254, not 192.168.0.0/24

Those two things fixed the Google Hub.

**The surprise:**
Maybe this was always the case, and I just didn’t realize it, when you add something to trusted_networks, they get to log in without passwords.  You select a user from the list and are logged in instantly.

Trusted_users is a bit of a misnomer to me.  I thought it was doing the heavy lifting for allowing direct sign-on, but no. All it does is limit the available user options in the dropdown for the listed IP address.  If there is only one user listed, that device auto-signs in as the user.  This would be more appropriately called something like “assigned_users”.  Great for dashboard hubs and tablets, bad for every other device on the network.

So, in my setup, with /24 at the trusted_network level, it means anyone accessing HA from within my home network that isn’t explicitly listed in “trusted_users” can pick from any one of the HA users and log in without password, including the admin account.  Yikes!

My fix was to create a “Guest” account and add a default trusted_user to the entire home network.  Now, any unlisted IP address gets “Guest” as the default option to sign in.  There is a toggle button at the bottom of the login that lets you switch over to the default HA login so a non-guest can log in.

I went this route instead of explicitly listing dashboard display device IPs as trusted_networks because now I can also tell guests they can control things on their phone with my reverse proxy website.  They just choose guest and away they go.

My final configuration.yaml looks like this:

```
homeassistant:
  auth_providers:
      - type: trusted_networks
        trusted_networks:
          - 192.168.0.0/24  # My main network
        trusted_users:
          192.168.0.10: HUB_USER_ID # Google Hub IP
          192.168.0.11: PHONE_USER_ID # Someones phone
          192.168.0.12: HUB_USER_ID # Another tablet for dashboard displays
          192.168.0.0/24: GUEST_USER_ID # All other devices can Guest into HA
      - type: homeassistant
```
I find I do not need the "allow_bypass_login: true"

To be clear, the HA documentation all very well explains this, but might be a little in the weeds for some people, especially if they are hacking together forum post suggestions.  I landed here because I was trying to do the same, but finally took the time to read the docs.
