### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by alexanderdominicnesbitt** [AlexxIT/DashCast#24]
Hey, was working great until the HASS core update 2024.10.3.

Casting reolink doorbell to nest hub. No problem with using the play media action to stream camera (it is just delayed)

Automation Casts video to 3 nest hubs when person is detected, stops casting when door opens or person no longer detected for 1 minute. Casting is blocked if front or garage door has been open within 
last 4 minutes. Automation YAML:

```
alias: Security - Camera - Cast hubs
description: ""
triggers:
  - entity_id:
      - binary_sensor.front_door_sensor_door_sensor_opening
    to: "on"
    id: DoorOpen
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 0
    trigger: state
    alias: Door open
  - entity_id:
      - binary_sensor.video_doorbell_person
    from: "off"
    to: "on"
    id: PersonPackage
    trigger: state
    alias: Detects person
  - alias: No longer detects person
    entity_id:
      - binary_sensor.video_doorbell_person
    from: "on"
    to: "off"
    id: Clear
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - PersonPackage
          - condition: state
            entity_id: binary_sensor.front_door_sensor_door_sensor_opening
            state: "off"
            for:
              hours: 0
              minutes: 4
              seconds: 0
          - condition: state
            for:
              hours: 0
              minutes: 4
              seconds: 0
            entity_id: cover.ratgdov25i_885e5d_door
            state: closed
        sequence:
          - action: webrtc.dash_cast
            metadata: {}
            data:
              force: true
              entity_id: media_player.nest_display_large
              entity: camera.video_doorbell_fluent
            enabled: true
          - action: webrtc.dash_cast
            metadata: {}
            data:
              entity_id: media_player.study_display
              entity: camera.video_doorbell_fluent
              force: true
          - action: webrtc.dash_cast
            metadata: {}
            data:
              entity_id: media_player.bedroom_display
              entity: camera.video_doorbell_fluent
              force: true
            enabled: true
        alias: Person detected
      - conditions:
          - condition: trigger
            id:
              - DoorOpen
              - Clear
        sequence:
          - action: media_player.turn_off
            metadata: {}
            data: {}
            target:
              entity_id:
                - media_player.nest_display_large
                - media_player.study_display
                - media_player.bedroom_display
        alias: Open door
mode: restart
```
